name: build

on:
  push:
    branches:
      - master
      - release
      - 'feature/**'
      - 'hotfix/**'
      - 'aws-lambda'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Output of required variable
        run: echo "Output -> ${{ github.event.pull_request.merged }}    ${{ github.event.action }}"

      - name: Testing
        if: github.event.action == 'opened' && github.event.pull_request.merged == false
        run: echo "RUNNING TESTS"

      - name: Skipping
        if: github.event.action == 'closed' && github.event.pull_request.merged == true
        run: echo "SKIPPING TESTS"
