name: build

on:
  push:
    branches:
      - master
      - release
      - 'feature/**'
      - 'hotfix/**'
      - 'aws-lambda'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Output of required variable
        run: echo "Output -> ${{ github.event.pull_request.merged }}"

      - name: Testing
        if: ${{ github.event.pull_request.merged !=true }}
        run: echo "RUNNING TESTS"

      - name: Skipping
        if: ${{ github.event.pull_request.merged ==true }}
        run: echo "SKIPPING TESTS"
