name: build

on:
  push:
    branches:
      - master
      - release
      - 'feature/**'
      - 'hotfix/**'
      - 'aws-lambda'
    tags:
      - r*
  pull_request:
    types:
      - closed
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Output of required variable
        run: echo "Output -> ${{ github.event.pull_request.merged }}"

      - name: PUSH EVENT
        if: ${{ github.event.pull_request.merged == ' ' }}
        run: echo "RUNNING TESTS"

      - name: PULL REQUEST MERGED
        if: ${{ github.event.pull_request.merged }}
        run: echo "SKIPPING TESTS"
